# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161117_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
