# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-17 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161117_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='learned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
